### ISSUE TITLE
Have you considered publishing your docker-manager.js?

### ISSUE THREAD

**Issue by arizonatribe** [BrunnerLivio/try#2]
Great tool you've built! I've just started using `dockerode` and I noticed you created a nice abstraction layer in your `docker-manager.js`, which resulted in a very readable control flow in your `index.js`. Have you considering publishing that as a separate tool?

**Comment by BrunnerLivio** [comment]
Thanks :)
I do not think so. The docker-manager.js is really tailored for the needs of this package. A good npm package should support more options, so if I'd extend my docker-manager, I would probably end up with a really similar package as `dockerode`. I do not think that would be a good idea.

Or why do you think so? `dockerode` is in my opinion really well built. It supports old fashioned callbacks, promises and streams. I couldn't ask for more.

**Comment by arizonatribe** [comment]
Perhaps there's a misunderstanding. I would have intended to work with both tools together (maybe all your docker manager would have needed is to mark a `peerDependency`). But since the NPM package installation isn't part of your docker manager, it seems to be very reusable. It's essentially there to pull images, create/remove containers, check if docker is installed, and stay attached to the stdin as it resizes.

I anticipate there will be pockets within the Node community that prefer orchestrating docker from NPM scripts inside their repo rather than the way we've traditionally gone of using Makefiles and/or bash scripts to manage images and containers.

Regardless, awesome tool and very well written code!

**Comment by BrunnerLivio** [comment]
Yes I see your point. I think its not a good idea though. I do not have the capability to maintain such a package
